import Link from "next/link";
export const metadata = { title: "Privacidade — Aprova UNIVESP" };
export default function Privacidade() {
  return <main className="max-w-3xl mx-auto p-6 md:p-12 space-y-6 leading-relaxed"><Link href="/" className="text-pen underline">Aprova UNIVESP</Link><h1 className="font-display text-3xl">Privacidade</h1><p>Responsável pelo serviço: Fabio VSena. Contato: <a href="mailto:fabiosena1436@gmail.com" className="underline">fabiosena1436@gmail.com</a>.</p>
    <h2 className="text-xl font-semibold">Dados e uso</h2><p>Guardamos nome, e-mail institucional, curso, senha protegida por hash, sessões de acesso, respostas de estudo, histórico, progresso de revisão e mensagens de atendimento. Esses dados permitem identificar sua conta, oferecer estudos e responder ao suporte. Administradores podem consultar contas e indicadores de uso; seu histórico não é mostrado a outros alunos.</p>
    <h2 className="text-xl font-semibold">Materiais e serviços externos</h2><p>O catálogo de matérias e questões é compartilhado com alunos autenticados. Administradores publicam o conteúdo. Quando a geração por IA está ativada, trechos dos materiais são enviados à API Gemini do Google. O envio de confirmação de e-mail e recuperação de senha usa Resend e inclui seu endereço e o link temporário. Não inclua dados pessoais desnecessários nos materiais.</p>
    <h2 className="text-xl font-semibold">Armazenamento no navegador</h2><p>Usamos um cookie de sessão para autenticação. Uma prova em andamento é guardada temporariamente na sessão do navegador para retomada e removida quando salva ou quando você sai. Não usamos cookies publicitários neste aplicativo.</p>
    <h2 className="text-xl font-semibold">Exportação e exclusão</h2><p>Você pode exportar seus dados e excluir a conta na página de perfil, confirmando sua senha. A exclusão remove seus dados pessoais, histórico e progresso. Conteúdo publicado no catálogo pode permanecer sem vínculo com sua conta. Solicitações de correção e dúvidas podem ser enviadas ao contato acima.</p>
    <h2 className="text-xl font-semibold">Retenção e segurança</h2><p>Dados da conta permanecem durante seu uso do serviço. Sessões expiram em 30 dias, links de recuperação em 30 minutos e links de confirmação em 24 horas. Registros de manutenção e auditoria têm retenção operacional de 90 dias. Cópias de segurança podem manter dados excluídos até o fim do ciclo de retenção de 30 dias. O responsável deve executar as rotinas de limpeza e backup documentadas para cumprir esses períodos.</p>
    <p className="text-sm text-muted">Atualizada em 2 de outubro de 2026.</p><Link href="/termos" className="text-pen underline">Termos de uso</Link></main>;
}
